# Generated by Django 6.0.2 on 2026-03-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_snippet_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(choices=[('py', 'Python'), ('js', 'javascript'), ('go', 'Golang'), ('cpp', 'C++'), ('html', 'HTML')], max_length=30),
        ),
    ]
